name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH 
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add VM to known hosts
        run: ssh-keyscan 4.233.193.30 >> ~/.ssh/known_hosts

      - name: SSH into Azure VM and get monitoring.sh
        run: |
          scp azureuser@4.233.193.30:/home/azureuser/monitoring.sh ./monitoring.sh

      - name: Run ShellCheck 
        run: |
          sudo apt-get install -y shellcheck
          shellcheck monitoring.sh

      - name: Set up git credentials
        run: |
          git config --global user.email "aleksandra.crnatovic@gmail.com"
          git config --global user.name "neoalexy"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          git config --global credential.helper 'store --file ~/.git-credentials'

      - name: Set git remote to HTTPS
        run: |
          git remote set-url origin https://github.com/neoalexy/Azure-VM-monitoring.git

      - name: Check git status
        run: git status

      - name: Commit any unstaged changes
        run: |
          git add monitoring.sh
          git commit -m "Auto commit before pull" || echo "No changes to commit"

      - name: Pull the latest changes from remote
        run: |
          git pull origin main --rebase

      - name: Push any new changes
        run: |
          git push origin main

      - name: Add monitoring.sh to repo and push
        run: |
          git add monitoring.sh
          git commit -m "Added script from Azure VM"
          git push -v origin main

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH 
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add VM to known hosts
        run: ssh-keyscan 4.233.193.30 >> ~/.ssh/known_hosts

      - name: Deploy monitoring.sh to Azure VM
        run: |
          scp monitoring.sh azureuser@4.233.193.30:/home/azureuser/monitoring.sh
          ssh azureuser@4.233.193.30 "chmod +x /home/azureuser/monitoring.sh && sudo systemctl restart monitoring"
