name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH 
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add VM to known hosts
        run: ssh-keyscan 4.233.193.30 >> ~/.ssh/known_hosts

      - name: SSH into Azure VM and get monitoring.sh
        run: |
          scp azureuser@4.233.193.30:/home/azureuser/monitoring.sh ./monitoring.sh

      - name: Run ShellCheck on monitoring.sh
        run: |
          sudo apt-get install -y shellcheck
          shellcheck monitoring.sh

      - name: Check if monitoring.sh has been modified
        run: |
          echo "Checking for changes in monitoring.sh"
          git diff monitoring.sh || echo "No changes in monitoring.sh"

      - name: Add timestamp to monitoring.sh
        run: |
          echo "Adding timestamp to monitoring.sh"
          echo "Last updated: $(date)" >> monitoring.sh

      - name: Check git status
        run: git status

      - name: Force add monitoring.sh to git
        run: |
          git add -f monitoring.sh
          git commit -m "Added timestamp to monitoring.sh" || echo "No changes to commit"
          git push -v origin main

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH 
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add VM to known hosts
        run: ssh-keyscan 4.233.193.30 >> ~/.ssh/known_hosts

      - name: Backup old script before deployment
        run: |
          ssh azureuser@4.233.193.30 "cp /home/azureuser/monitoring.sh /home/azureuser/monitoring.sh.bak"

      - name: Deploy monitoring.sh to Azure VM
        run: |
          scp monitoring.sh azureuser@4.233.193.30:/home/azureuser/monitoring.sh
          ssh azureuser@4.233.193.30 "chmod +x /home/azureuser/monitoring.sh && sudo systemctl restart monitoring"

      - name: Health check after deployment
        run: |
          ssh azureuser@4.233.193.30 "tail -n 20 /var/log/sys-monitoring.log | grep 'Monitoring finished' || (echo 'Health check failed, rolling back...' && mv /home/azureuser/monitoring.sh.bak /home/azureuser/monitoring.sh && sudo systemctl restart monitoring)"
